INFO - 2024-06-05 06:58:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-06-05 06:58:15 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-06-05 06:58:15 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-06-05 06:58:15 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u378733989_turing_people'@'localhost' (using password: YES) in C:\xampp\htdocs\Turing-IA\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Turing-IA\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'u378733989_turi...', 'Turing_people_l...', 'u378733989_turi...', 3306, '', 0)
#1 C:\xampp\htdocs\Turing-IA\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Turing-IA\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Turing-IA\app\Models\AuthModel.php(20): CodeIgniter\Database\BaseConnection->query('SELECT colabora...', Array)
#4 C:\xampp\htdocs\Turing-IA\app\Controllers\AuthController.php(72): App\Models\AuthModel->login('capitalhumano@t...')
#5 C:\xampp\htdocs\Turing-IA\system\CodeIgniter.php(942): App\Controllers\AuthController->index()
#6 C:\xampp\htdocs\Turing-IA\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#7 C:\xampp\htdocs\Turing-IA\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Turing-IA\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\Turing-IA\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Turing-IA\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Turing-IA\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Turing-IA\app\Models\AuthModel.php(20): CodeIgniter\Database\BaseConnection->query('SELECT colabora...', Array)
#3 C:\xampp\htdocs\Turing-IA\app\Controllers\AuthController.php(72): App\Models\AuthModel->login('capitalhumano@t...')
#4 C:\xampp\htdocs\Turing-IA\system\CodeIgniter.php(942): App\Controllers\AuthController->index()
#5 C:\xampp\htdocs\Turing-IA\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#6 C:\xampp\htdocs\Turing-IA\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\Turing-IA\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-06-05 06:58:15 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\AuthModel.php(20): CodeIgniter\Database\BaseConnection->query('SELECT colaboradores.id, colaboradores.nombre, colaboradores.correo, 
        colaboradores.password, areas.descripcion, areas.puesto, colaboradores.rol, colaboradores.ip
        FROM colaboradores
        INNER JOIN areas ON colaboradores.id = areas.id_usuario 
        LEFT JOIN datos_personales ON datos_personales.id_usuario = colaboradores.id
        WHERE colaboradores.correo = ?
        AND datos_personales.fecha_egreso = 0', [...])
 3 APPPATH\Controllers\AuthController.php(72): App\Models\AuthModel->login('capitalhumano@turing-latam.com')
 4 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\AuthController->index()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-06-05 06:58:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-06-05 06:59:09 --> Error connecting to the database: mysqli_sql_exception: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.
 in C:\xampp\htdocs\Turing-IA\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Turing-IA\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('turing-latam.co...', 'u378733989_turi...', 'Turing_people_l...', 'u378733989_turi...', 3306, '', 0)
#1 C:\xampp\htdocs\Turing-IA\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Turing-IA\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Turing-IA\app\Models\AuthModel.php(20): CodeIgniter\Database\BaseConnection->query('SELECT colabora...', Array)
#4 C:\xampp\htdocs\Turing-IA\app\Controllers\AuthController.php(72): App\Models\AuthModel->login('capitalhumano@t...')
#5 C:\xampp\htdocs\Turing-IA\system\CodeIgniter.php(942): App\Controllers\AuthController->index()
#6 C:\xampp\htdocs\Turing-IA\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#7 C:\xampp\htdocs\Turing-IA\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Turing-IA\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.
 in C:\xampp\htdocs\Turing-IA\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Turing-IA\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Turing-IA\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Turing-IA\app\Models\AuthModel.php(20): CodeIgniter\Database\BaseConnection->query('SELECT colabora...', Array)
#3 C:\xampp\htdocs\Turing-IA\app\Controllers\AuthController.php(72): App\Models\AuthModel->login('capitalhumano@t...')
#4 C:\xampp\htdocs\Turing-IA\system\CodeIgniter.php(942): App\Controllers\AuthController->index()
#5 C:\xampp\htdocs\Turing-IA\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#6 C:\xampp\htdocs\Turing-IA\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\Turing-IA\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-06-05 06:59:09 --> Unable to connect to the database.
Main connection [MySQLi]: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.

in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\AuthModel.php(20): CodeIgniter\Database\BaseConnection->query('SELECT colaboradores.id, colaboradores.nombre, colaboradores.correo, 
        colaboradores.password, areas.descripcion, areas.puesto, colaboradores.rol, colaboradores.ip
        FROM colaboradores
        INNER JOIN areas ON colaboradores.id = areas.id_usuario 
        LEFT JOIN datos_personales ON datos_personales.id_usuario = colaboradores.id
        WHERE colaboradores.correo = ?
        AND datos_personales.fecha_egreso = 0', [...])
 3 APPPATH\Controllers\AuthController.php(72): App\Models\AuthModel->login('capitalhumano@turing-latam.com')
 4 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\AuthController->index()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-06-05 07:00:44 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-06-05 07:00:58 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-06-05 07:00:58 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: Host desconocido.  in C:\xampp\htdocs\Turing-IA\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 185, Array)
#1 C:\xampp\htdocs\Turing-IA\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('149.100.151.174...', 'u378733989_turi...', 'Turing_people_l...', 'u378733989_turi...', 3306, '', 0)
#2 C:\xampp\htdocs\Turing-IA\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\Turing-IA\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\Turing-IA\app\Models\AuthModel.php(20): CodeIgniter\Database\BaseConnection->query('SELECT colabora...', Array)
#5 C:\xampp\htdocs\Turing-IA\app\Controllers\AuthController.php(72): App\Models\AuthModel->login('capitalhumano@t...')
#6 C:\xampp\htdocs\Turing-IA\system\CodeIgniter.php(942): App\Controllers\AuthController->index()
#7 C:\xampp\htdocs\Turing-IA\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 C:\xampp\htdocs\Turing-IA\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Turing-IA\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo failed: Host desconocido.  in C:\xampp\htdocs\Turing-IA\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Turing-IA\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('149.100.151.174...', 'u378733989_turi...', 'Turing_people_l...', 'u378733989_turi...', 3306, '', 0)
#1 C:\xampp\htdocs\Turing-IA\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Turing-IA\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Turing-IA\app\Models\AuthModel.php(20): CodeIgniter\Database\BaseConnection->query('SELECT colabora...', Array)
#4 C:\xampp\htdocs\Turing-IA\app\Controllers\AuthController.php(72): App\Models\AuthModel->login('capitalhumano@t...')
#5 C:\xampp\htdocs\Turing-IA\system\CodeIgniter.php(942): App\Controllers\AuthController->index()
#6 C:\xampp\htdocs\Turing-IA\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#7 C:\xampp\htdocs\Turing-IA\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Turing-IA\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo failed: Host desconocido.  in C:\xampp\htdocs\Turing-IA\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Turing-IA\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Turing-IA\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Turing-IA\app\Models\AuthModel.php(20): CodeIgniter\Database\BaseConnection->query('SELECT colabora...', Array)
#3 C:\xampp\htdocs\Turing-IA\app\Controllers\AuthController.php(72): App\Models\AuthModel->login('capitalhumano@t...')
#4 C:\xampp\htdocs\Turing-IA\system\CodeIgniter.php(942): App\Controllers\AuthController->index()
#5 C:\xampp\htdocs\Turing-IA\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#6 C:\xampp\htdocs\Turing-IA\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\Turing-IA\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-06-05 07:00:58 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: Host desconocido. 
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\AuthModel.php(20): CodeIgniter\Database\BaseConnection->query('SELECT colaboradores.id, colaboradores.nombre, colaboradores.correo, 
        colaboradores.password, areas.descripcion, areas.puesto, colaboradores.rol, colaboradores.ip
        FROM colaboradores
        INNER JOIN areas ON colaboradores.id = areas.id_usuario 
        LEFT JOIN datos_personales ON datos_personales.id_usuario = colaboradores.id
        WHERE colaboradores.correo = ?
        AND datos_personales.fecha_egreso = 0', [...])
 3 APPPATH\Controllers\AuthController.php(72): App\Models\AuthModel->login('capitalhumano@turing-latam.com')
 4 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\AuthController->index()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-06-05 07:01:01 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-06-05 07:01:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-06-05 07:01:48 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-06-05 07:01:48 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-06-05 07:01:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-06-05 07:01:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-06-05 07:02:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-06-05 07:02:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-06-05 20:54:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
